//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_info
    {
        public int Id { get; set; }
        public System.DateTime DateofBirth { get; set; }
        public string email { get; set; }
        public int phone_num { get; set; }
        public string Class { get; set; }
        public string emergency_contract { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
